# Discord Bot Translator Configuration

logging:
  # Console logging level: 'DEBUG' or 'INFO'
  # DEBUG: Shows all log messages on console  # INFO: Shows only INFO and above on console
  console_level: 'INFO'
  
  # File logging is always DEBUG regardless of console_level
  file_level: 'DEBUG'
  
  # Maximum log file size in MB
  max_file_size: 10
  
  # Number of backup log files to keep (plus 1 current = 5 total files)
  backup_count: 4

# Model configuration
models:
  # Accurate tier - high-quality models for accuracy
  accurate:
    name: "large-v3-turbo"
    # name: "base"
    count: 1
    description: "High-accuracy transcription"
    device: "cuda"
    warmup_timeout: 30
    
  # Fast tier - small, fast models for speed and parallelization  
  fast:
    name: "base"
    count: 3
    description: "Fast parallel transcription"
    device: "cuda"
    warmup_timeout: 30
    min_pool_size: 1
    max_pool_size: 5
  
audio:
  # Audio processing configuration will go here
  
discord:
  # Discord bot configuration will go here

translation:
  # DeepL API configuration
  deepl_api_key: "5ac935ea-9ed2-40a7-bd4d-8153c941c79f:fx"  # Replace with your DeepL API key
  deepl_api_url: "https://api-free.deepl.com/v2/translate"   # Use https://api.deepl.com/v2/translate for paid accounts
  target_language: "EN"  # Target language for translation
  timeout: 10  # Request timeout in seconds
